# Generated by Django 6.0.4 on 2026-04-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroimage',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='nailgalleryimage',
            name='image_url',
        ),
        migrations.AddField(
            model_name='heroimage',
            name='image',
            field=models.ImageField(help_text='Upload an image for the Hero section', null=True, upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='nailgalleryimage',
            name='image',
            field=models.ImageField(help_text='Upload an image for the nail gallery section', null=True, upload_to='gallery/'),
        ),
    ]
